// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
export const C = {
  bg:      '#040810',
  bgPanel: '#080F1C',
  bgCard:  '#0C1526',
  bgInput: '#06101E',
  bgHover: '#0F1A2E',
  border:      '#0E1E35',
  borderMid:   '#162640',
  borderBright:'#1E3560',
  cyan:   '#00D4FF',
  amber:  '#FF8B00',
  green:  '#00E8A2',
  red:    '#FF3D5A',
  purple: '#9D6FFF',
  blue:   '#3B82F6',
  yellow: '#FFD100',
  pink:   '#FF6FD8',
  text:      '#C4D4E8',
  textSub:   '#4A6080',
  textMute:  '#1E3050',
  white:     '#F0F8FF',
};

// ─── NAVIGATION TREE ──────────────────────────────────────────────────────────
export const NAV = [
  { id:'home',  icon:'⬡', label:'Command Center', section:'core' },
  { id:'chat',  icon:'◈', label:'SAP Sage AI',     section:'core', badge:'AI' },
  { id:'_sep1', separator:true, label:'SAP LANDSCAPES' },
  { id:'ecc', icon:'▣', label:'SAP ECC 6.0', section:'landscape', children:[
    { id:'ecc-fi',   label:'FI / CO',          color:'#00E8A2' },
    { id:'ecc-mm',   label:'MM / WM',          color:'#FF8B00' },
    { id:'ecc-sd',   label:'SD',               color:'#00D4FF' },
    { id:'ecc-pm',   label:'PM / EAM',         color:'#9D6FFF' },
    { id:'ecc-qm',   label:'QM',               color:'#FF3D5A' },
    { id:'ecc-pp',   label:'PP',               color:'#FFD100' },
    { id:'ecc-hcm',  label:'HCM / HR',         color:'#FF6FD8' },
    { id:'ecc-ps',   label:'PS',               color:'#3B82F6' },
    { id:'ecc-ale',  label:'ALE / IDoc',       color:'#00D4FF' },
    { id:'ecc-basis',label:'Basis / Security', color:'#4A6080' },
  ]},
  { id:'s4op', icon:'▣', label:'S/4HANA On-Premise', section:'landscape', children:[
    { id:'s4op-fi',    label:'FI / CO',           color:'#00E8A2' },
    { id:'s4op-mm',    label:'MM / EWM',          color:'#FF8B00' },
    { id:'s4op-sd',    label:'SD / TM',           color:'#00D4FF' },
    { id:'s4op-pm',    label:'PM / EAM',          color:'#9D6FFF' },
    { id:'s4op-pp',    label:'PP / MRP Live',     color:'#FFD100' },
    { id:'s4op-rap',   label:'RAP / OData',       color:'#00E8A2' },
    { id:'s4op-fiori', label:'Fiori / UI5',       color:'#00D4FF' },
    { id:'s4op-ext',   label:'Extensibility',     color:'#FF6FD8' },
  ]},
  { id:'s4pub', icon:'▣', label:'S/4HANA Public Cloud', section:'landscape', children:[
    { id:'s4pub-kue',  label:'Key User Extensions', color:'#00E8A2' },
    { id:'s4pub-side', label:'Side-by-Side Ext.',   color:'#FF8B00' },
    { id:'s4pub-api',  label:'Released APIs',       color:'#00D4FF' },
    { id:'s4pub-evts', label:'Business Events',     color:'#9D6FFF' },
  ]},
  { id:'s4pc', icon:'▣', label:'S/4HANA Private Cloud', section:'landscape', children:[
    { id:'s4pc-ext', label:'Extensibility Rules', color:'#FF8B00' },
    { id:'s4pc-ops', label:'Operations / Basis',  color:'#4A6080' },
    { id:'s4pc-intg',label:'BTP Integration',     color:'#3B82F6' },
  ]},
  { id:'sf', icon:'◆', label:'SAP SuccessFactors', section:'landscape', children:[
    { id:'sf-ec',   label:'Employee Central',    color:'#FF8B00' },
    { id:'sf-rcm',  label:'Recruiting (RCM)',    color:'#00E8A2' },
    { id:'sf-lms',  label:'Learning (LMS)',      color:'#9D6FFF' },
    { id:'sf-pm',   label:'Performance & Goals', color:'#00D4FF' },
    { id:'sf-comp', label:'Compensation',        color:'#FFD100' },
    { id:'sf-api',  label:'API / Integration',  color:'#3B82F6' },
  ]},
  { id:'ariba', icon:'◆', label:'SAP Ariba', section:'landscape', children:[
    { id:'ariba-proc',  label:'Procurement',    color:'#FF8B00' },
    { id:'ariba-cntrt', label:'Contracts',      color:'#00E8A2' },
    { id:'ariba-sup',   label:'Supplier Mgmt',  color:'#9D6FFF' },
    { id:'ariba-api',   label:'Open API',       color:'#3B82F6' },
  ]},
  { id:'others', icon:'◆', label:'Other Landscapes', section:'landscape', children:[
    { id:'oth-concur', label:'SAP Concur',            color:'#00D4FF' },
    { id:'oth-mdi',    label:'Master Data Integ.',    color:'#FF8B00' },
    { id:'oth-mdg',    label:'Master Data Gov.',      color:'#00E8A2' },
    { id:'oth-dms',    label:'Document Mgmt (DMS)',   color:'#9D6FFF' },
    { id:'oth-ibp',    label:'SAP IBP',               color:'#FFD100' },
    { id:'oth-bw',     label:'BW/4HANA',              color:'#3B82F6' },
    { id:'oth-grc',    label:'GRC',                   color:'#FF3D5A' },
  ]},
  { id:'_sep2', separator:true, label:'BTP PLATFORM' },
  { id:'btp',      icon:'⬡', label:'BTP Overview',         section:'btp' },
  { id:'intgsuite',icon:'⬡', label:'Integration Suite',    section:'btp', children:[
    { id:'is-cpi',  label:'Cloud Integration (CPI)', color:'#00D4FF' },
    { id:'is-apim', label:'API Management',          color:'#FF8B00' },
    { id:'is-em',   label:'Event Mesh',              color:'#9D6FFF' },
    { id:'is-ia',   label:'Integration Advisor',     color:'#00E8A2' },
    { id:'is-oc',   label:'Open Connectors',         color:'#FFD100' },
    { id:'is-tpm',  label:'Trading Partner Mgmt',    color:'#3B82F6' },
  ]},
  { id:'btpdev', icon:'⬡', label:'Dev / Runtime', section:'btp', children:[
    { id:'dev-abap', label:'ABAP Environment',   color:'#00D4FF' },
    { id:'dev-cf',   label:'Cloud Foundry',      color:'#FF8B00' },
    { id:'dev-kyma', label:'Kyma Runtime',       color:'#9D6FFF' },
    { id:'dev-bas',  label:'Business App Studio',color:'#00E8A2' },
  ]},
  { id:'btpbuild', icon:'⬡', label:'SAP Build', section:'btp', children:[
    { id:'build-spa',  label:'Process Automation', color:'#FF8B00' },
    { id:'build-apps', label:'Build Apps',         color:'#00D4FF' },
    { id:'build-wz',   label:'Work Zone',          color:'#00E8A2' },
  ]},
  { id:'btpdata', icon:'⬡', label:'Data & AI', section:'btp', children:[
    { id:'data-hana', label:'HANA Cloud',        color:'#FFD100' },
    { id:'data-sac',  label:'Analytics Cloud',   color:'#3B82F6' },
    { id:'data-ai',   label:'AI Core',           color:'#9D6FFF' },
    { id:'data-dsp',  label:'Datasphere',        color:'#00E8A2' },
  ]},
  { id:'_sep3', separator:true, label:'TECHNICAL' },
  { id:'abap', icon:'◉', label:'ABAP Development', section:'tech', children:[
    { id:'abap-classic', label:'Classic ABAP / OO',      color:'#00D4FF' },
    { id:'abap-cloud',   label:'ABAP Cloud (Clean Core)', color:'#00E8A2' },
    { id:'abap-hana',    label:'ABAP for HANA',          color:'#FFD100' },
    { id:'abap-enh',     label:'Enhancement Framework',  color:'#9D6FFF' },
    { id:'abap-forms',   label:'Forms (Adobe/Script)',   color:'#FF6FD8' },
  ]},
  { id:'rap', icon:'◉', label:'RAP / OData', section:'tech', children:[
    { id:'rap-cds',  label:'CDS Views',               color:'#00D4FF' },
    { id:'rap-bdef', label:'Behavior Definition',     color:'#00E8A2' },
    { id:'rap-impl', label:'Behavior Implementation', color:'#FF8B00' },
    { id:'rap-v4',   label:'OData V4 / V2',           color:'#9D6FFF' },
  ]},
  { id:'fiori', icon:'◉', label:'Fiori / UI5', section:'tech', children:[
    { id:'fiori-elem',  label:'Fiori Elements',    color:'#00D4FF' },
    { id:'fiori-ui5',   label:'SAPUI5 Custom',     color:'#FF8B00' },
    { id:'fiori-anno',  label:'CDS Annotations',   color:'#00E8A2' },
    { id:'fiori-lp',    label:'Launchpad Config',  color:'#9D6FFF' },
  ]},
  { id:'cap', icon:'◉', label:'CAP Full Stack',    section:'tech' },
  { id:'ext', icon:'◉', label:'Extensibility',     section:'tech' },
  { id:'spa', icon:'◉', label:'Process Automation',section:'tech' },
  { id:'wf',  icon:'◉', label:'Workflow',          section:'tech' },
  { id:'_sep4', separator:true, label:'DOCUMENTATION' },
  { id:'doc-sdd',  icon:'▪', label:'Software Design Doc',    section:'docs' },
  { id:'doc-tech', icon:'▪', label:'Technical Spec',         section:'docs' },
  { id:'doc-intg', icon:'▪', label:'Integration Design Doc', section:'docs' },
  { id:'doc-impl', icon:'▪', label:'Implementation Guide',   section:'docs' },
  { id:'doc-step', icon:'▪', label:'Step-by-Step Guide',     section:'docs' },
  { id:'doc-api',  icon:'▪', label:'API Documentation',      section:'docs' },
  { id:'doc-test', icon:'▪', label:'Test Plan',              section:'docs' },
  { id:'_sep5', separator:true, label:'TOOLS' },
  { id:'codegen',  icon:'⟡', label:'Code Generator',     section:'tools' },
  { id:'txfinder', icon:'⟡', label:'Transaction Finder', section:'tools' },
  { id:'wizard',   icon:'⟡', label:'Config Wizards',     section:'tools' },
  { id:'apiref',   icon:'⟡', label:'API Reference',      section:'tools' },
];

// ─── TRANSACTIONS ─────────────────────────────────────────────────────────────
export const TRANSACTIONS = [
  // BASIS
  ['SM59','BASIS','RFC Destinations','Connectivity'],
  ['STRUST','BASIS','SSL Certificate Manager','Security'],
  ['SM21','BASIS','System Log','Monitoring'],
  ['SM50','BASIS','Work Process Overview','Performance'],
  ['SM37','BASIS','Job Monitor','Scheduler'],
  ['SM36','BASIS','Schedule Background Job','Scheduler'],
  ['PFCG','BASIS','Role Maintenance','Authorization'],
  ['SU01','BASIS','User Maintenance','Authorization'],
  ['SPRO','BASIS','Customizing / IMG','Config'],
  ['SLG1','BASIS','Application Log Viewer','Monitoring'],
  ['SM30','BASIS','Table Maintenance','Config'],
  ['AL11','BASIS','SAP File System Directories','Files'],
  ['SM12','BASIS','Lock Entries','Performance'],
  ['RZ10','BASIS','Profile Parameter Maintenance','Config'],
  ['SICK','BASIS','Installation Check','Basis'],
  ['SMLG','BASIS','Logon Groups','Basis'],
  ['STMS','BASIS','Transport Management System','Transport'],
  ['SE06','BASIS','Set Up Workbench Organizer','Transport'],
  ['SCC4','BASIS','Client Administration','Basis'],
  // ABAP
  ['SE38','ABAP','ABAP Program Editor','Dev'],
  ['SE80','ABAP','Object Navigator / Repository','Dev'],
  ['SE11','ABAP','ABAP Dictionary','Dev'],
  ['SE16','ABAP','Data Browser','Data'],
  ['SE16N','ABAP','General Table Display','Data'],
  ['SE24','ABAP','Class Builder','Dev'],
  ['SE37','ABAP','Function Module Editor','Dev'],
  ['SE41','ABAP','Menu Painter','Dev'],
  ['SE51','ABAP','Screen Painter','Dev'],
  ['SE93','ABAP','Transaction Maintenance','Dev'],
  ['SE18','ABAP','BAdI Builder','Enhancement'],
  ['SE19','ABAP','BAdI Implementation','Enhancement'],
  ['ST05','ABAP','SQL Performance Trace','Performance'],
  ['SAT','ABAP','ABAP Runtime Analysis','Performance'],
  ['SCI','ABAP','Code Inspector','Quality'],
  ['SLIN','ABAP','Extended Syntax Check','Quality'],
  ['SHDB','ABAP','Batch Input Recorder','Dev'],
  // ALE / IDoc
  ['WE81','ALE','Message Type Maintenance','IDoc'],
  ['WE31','ALE','IDoc Basic Type Editor','IDoc'],
  ['WE82','ALE','Assign IDoc to Message Type','IDoc'],
  ['WE05','ALE','IDoc Monitor','IDoc'],
  ['WE09','ALE','Search IDoc','IDoc'],
  ['WE19','ALE','Test IDoc Processing','IDoc'],
  ['BD64','ALE','Distribution Model Maintenance','ALE'],
  ['BD61','ALE','Activate Change Pointers (Global)','ALE'],
  ['BD50','ALE','Activate CP per Message Type','ALE'],
  ['BD52','ALE','Change Doc Fields for MsgType','ALE'],
  ['SWE2','ALE','Event Type Linkages (BUS Objects)','Events'],
  ['SWO1','ALE','Business Object Builder','Events'],
  ['RBDMIDOC','ALE','Generate IDocs from Change Pointers','ALE'],
  ['BD87','ALE','Post IDoc Status Manually','IDoc'],
  ['/ASADEV/ACI_MONITOR','EEM','Event Enablement Add-on Monitor','EventEnablement'],
  ['RASANWEE_CHECK','EEM','ASANWEE Health Check','EventEnablement'],
  // FI / CO
  ['FB01','FI','Post Document','Posting'],
  ['FB03','FI','Display FI Document','Display'],
  ['FB50','FI','G/L Account Document Entry','G/L'],
  ['FB60','FI','Enter Vendor Invoice','AP'],
  ['FB70','FI','Enter Customer Invoice','AR'],
  ['F-53','FI','Post Outgoing Payments','AP'],
  ['F-28','FI','Post Incoming Payments','AR'],
  ['F-32','FI','Clear Customer Open Items','AR'],
  ['F110','FI','Automatic Payment Program','AP'],
  ['FS00','FI','G/L Account Master Record','MasterData'],
  ['FK01','FI','Create Vendor Master (FI)','MasterData'],
  ['FD01','FI','Create Customer Master','MasterData'],
  ['FBL1N','FI','Vendor Line Item Display','Reports'],
  ['FBL3N','FI','G/L Line Item Display','Reports'],
  ['FBL5N','FI','Customer Line Item Display','Reports'],
  ['F.01','FI','Balance Sheet / P&L Statement','Reports'],
  ['FAGLB03','FI','G/L Account Balance (New G/L)','Reports'],
  ['MR11','FI','GR/IR Account Maintenance','Clearing'],
  ['KE30','CO','CO-PA Report Execution','CO-PA'],
  ['KSB1','CO','Cost Center Line Items','CO'],
  ['KO01','CO','Create Internal Order','CO'],
  ['CJI3','PS','Project Actual Line Items','PS'],
  // MM
  ['ME21N','MM','Create Purchase Order','Procurement'],
  ['ME22N','MM','Change Purchase Order','Procurement'],
  ['ME23N','MM','Display Purchase Order','Procurement'],
  ['ME51N','MM','Create Purchase Requisition','Procurement'],
  ['ME52N','MM','Change Purchase Requisition','Procurement'],
  ['MIGO','MM','Goods Movement (GR/GI/Transfer)','Inventory'],
  ['MMBE','MM','Stock Overview','Inventory'],
  ['MB52','MM','Warehouse Stocks of Material','Inventory'],
  ['MB51','MM','Material Document List','Inventory'],
  ['MIRO','MM','Enter Incoming Invoice (LIV)','Invoice'],
  ['MIR7','MM','Park Incoming Invoice','Invoice'],
  ['MM01','MM','Create Material Master','MasterData'],
  ['MM60','MM','Material Where-Used List','MasterData'],
  ['MK01','MM','Create Vendor Master (MM)','MasterData'],
  ['ME2N','MM','Purchase Orders by PO Number','Reports'],
  ['ME2M','MM','Purchase Orders by Material','Reports'],
  // SD
  ['VA01','SD','Create Sales Order','Orders'],
  ['VA02','SD','Change Sales Order','Orders'],
  ['VA03','SD','Display Sales Order','Orders'],
  ['VL01N','SD','Create Outbound Delivery','Shipping'],
  ['VL02N','SD','Change Outbound Delivery','Shipping'],
  ['VF01','SD','Create Billing Document','Billing'],
  ['VF03','SD','Display Billing Document','Billing'],
  ['VKM3','SD','Release Credit-Blocked SD Documents','Credit'],
  ['XD01','SD','Create Customer Master (Central)','MasterData'],
  ['VK11','SD','Create Pricing Condition Record','Pricing'],
  ['V/06','SD','Pricing Condition Type Config','Config'],
  ['OVK1','SD','Sales Document Types','Config'],
  ['VD01','SD','Create Customer Master (SD)','MasterData'],
  // PM
  ['IW21','PM','Create PM Notification','Notifications'],
  ['IW22','PM','Change PM Notification','Notifications'],
  ['IW29','PM','Display PM Notifications','Notifications'],
  ['IW31','PM','Create Work Order','Orders'],
  ['IW32','PM','Change Work Order','Orders'],
  ['IW38','PM','Mass Change PM Orders','Orders'],
  ['IW36','PM','Create PM Sub-Order','Orders'],
  ['IL01','PM','Create Functional Location','MasterData'],
  ['IL03','PM','Display Functional Location','MasterData'],
  ['IE01','PM','Create Equipment Master','MasterData'],
  ['IE03','PM','Display Equipment Master','MasterData'],
  ['IP01','PM','Create Maintenance Plan','Planning'],
  ['IP10','PM','Maintenance Plan Scheduling','Planning'],
  ['IA05','PM','Change Task List (General)','Planning'],
  // QM / PP
  ['QM01','QM','Create Quality Notification','QM'],
  ['QE01','QM','Enter Results for Inspection Lot','QM'],
  ['QA01','QM','Create Inspection Lot','QM'],
  ['QS21','QM','Create Master Inspection Char.','QM'],
  ['MD01','PP','Run MRP for Plant','PP'],
  ['MD04','PP','Stock/Requirements List','PP'],
  ['CO01','PP','Create Production Order','PP'],
  ['CO02','PP','Change Production Order','PP'],
  ['COOIS','PP','Production Order Information','PP'],
  ['CA01','PP','Create Routing','PP'],
  ['CS01','PP','Create Bill of Materials','PP'],
  // CPI / BTP
  ['CPI-Monitor','CPI','Message Monitor (CPI)','Integration'],
  ['APIM-Portal','APIM','API Management Portal','Integration'],
  ['EM-App','EM','Event Mesh Application','Integration'],
];

// ─── SECTION COLORS ────────────────────────────────────────────────────────────
export const SECTION_COLOR = {
  core:'#FF8B00', landscape:'#00D4FF', btp:'#00E8A2',
  tech:'#9D6FFF', docs:'#3B82F6', tools:'#4A6080',
};

// ─── CONTEXT-AWARE QUICK PROMPTS ──────────────────────────────────────────────
export const QUICK_PROMPTS = {
  default: [
    'How do I configure ECC PM Notifications to SAP Event Mesh using ASANWEE?',
    'Generate a CPI Groovy script to parse IDoc XML and extract QMNUM',
    'Compare S/4HANA Public Cloud vs Private Cloud extensibility options',
    'Walk me through RAP BO with draft handling for a custom Z table',
    'What BTP services do I need for side-by-side extension on S/4HANA Cloud?',
    'How does SuccessFactors Employee Central integrate with S/4HANA HR?',
  ],
  'ecc-fi':  ['Key tables for FI document header/line items in ECC?','How does new G/L document splitting work?','Configure automatic payment program F110 step-by-step'],
  'ecc-pm':  ['Configure preventive maintenance plans IP01/IP10','BUS2080 event flow for PM Notification CREATED','Set up equipment hierarchy with functional locations'],
  'ecc-ale': ['How do I configure SWE2 for BUS2080 CREATED event?','What is the correct FM for ASANWEE event dispatch?','How does RBDMIDOC generate IDocs from change pointers?'],
  'is-cpi':  ['How to handle CSRF token in CPI for OData POST?','Write Groovy to parse IDoc and route by message type','Configure error handling with dead letter queue in CPI'],
  'is-em':   ['How to subscribe CPI AMQP adapter to Event Mesh queue?','CloudEvents 1.0 structure for SAP ECC events','Event Mesh service key — which fields go where?'],
  's4pub-api':['What released APIs exist for purchase orders in S/4 Cloud?','How to handle pagination in S/4HANA Cloud OData APIs?','Consume API_PURCHASEORDER_PROCESS_SRV in CPI'],
  'abap-cloud':['What are released ABAP APIs for reading sales orders?','How to call OData V4 API from ABAP Cloud?','Clean core compliance rules for Private Cloud'],
  'rap-bdef': ['Full RAP BDEF syntax for managed BO with draft','Implement determinations and validations in RAP','RAP actions: instance vs static, with return parameter'],
  'sf-api':   ['Read SuccessFactors employee data via OData V2','Difference between SFAPI and OData in SuccessFactors','Integrate SF Employee Central with SAP ECC via CPI'],
  'ariba-api':['Call SAP Ariba Open API for purchase orders','Ariba Network API authentication setup','Ariba Network integration with S/4HANA via CPI'],
};

// ─── DOC TYPE METADATA ────────────────────────────────────────────────────────
export const DOC_META = {
  'doc-sdd':  { title:'Software Design Document (SDD)',   color:'#00D4FF', desc:'System design, architecture, components, data models, integrations, security, deployment.' },
  'doc-tech': { title:'Technical Specification',         color:'#FF8B00', desc:'Exact configs, FMs, tables, fields, transactions, code snippets — precise technical detail.' },
  'doc-intg': { title:'Integration Design Document (IDD)',color:'#00E8A2', desc:'Source/target systems, payload mapping, adapters, auth, error handling, monitoring.' },
  'doc-impl': { title:'Implementation Guide',            color:'#9D6FFF', desc:'Phased implementation with prerequisites, configs, customizing, testing, go-live checklist.' },
  'doc-step': { title:'Step-by-Step Solution Guide',     color:'#FFD100', desc:'Numbered steps, SPRO paths, transaction codes, verification steps per scenario.' },
  'doc-api':  { title:'API Documentation (OpenAPI)',     color:'#FF6FD8', desc:'Endpoints, methods, payloads, auth, error codes, curl examples — full API reference.' },
  'doc-test': { title:'Test Plan & Test Cases',          color:'#FF3D5A', desc:'Unit, integration, UAT, regression, performance test cases with expected results.' },
};

// ─── MASTER AI SYSTEM PROMPT ──────────────────────────────────────────────────
export const SYSTEM_PROMPT = `You are SAP Sage — the definitive AI assistant for the full SAP ecosystem. You are an elite SAP architect, developer, and consultant combined.

LANDSCAPES: SAP ECC 6.0 (all EhPs), S/4HANA On-Premise (1511–2023), S/4HANA Private Cloud, S/4HANA Public Cloud, SuccessFactors (EC/RCM/LMS/PMgmt/Comp/WFA), SAP Ariba (Procurement/Contracts/Network), SAP Concur, Master Data Integration (MDI), Master Data Governance (MDG), Document Management (DMS), IBP, BW/4HANA, GRC, SRM, TM, EWM, RE-FX

MODULES: FI (G/L, AP, AR, AA, Bank, New G/L, Doc Splitting), CO (CostCenters, ProfitCenters, InternalOrders, ProductCosting, CO-PA), MM (Purchasing, IM, LIV, WM, Batch), SD (Orders, Delivery, Billing, Pricing, Credit, RR), PP (MRP, ProdOrders, Routings, BOM, Capacity, KANBAN), PM/EAM (Equipment, FuncLoc, Notifications, WOs, PreventiveMaint), QM (InspLots, QualityNotifs, CtrlCharts), PS (WBS, Networks, Milestones), HCM (PA, Payroll, TM, OM), GRC (AC, PC, RM, GT), RE-FX (IFRS16 Leases)

BTP: Integration Suite (CPI, APIM, Event Mesh, IA, OpenConnectors, TPM, MigrationToolkit), ABAP Environment (ABAP Cloud, RAP, ADT, ATC, Released APIs), SAP Build (Process Automation, Apps, Work Zone, Code/Joule), HANA Cloud, Analytics Cloud, Datasphere, AI Core+Launchpad, Data Intelligence, Identity (IAS, IPS, XSUAA), Cloud Foundry, Kyma, BAS, Mobile Services, Connectivity, Destination, Private Link, Alert Notification, Job Scheduling, Cloud Logging

TECHNICAL: ABAP (Classic, OO, HANA push-down, Cloud/Clean Core), RAP (CDS Views, BDEF, Behavior Implementation, Draft, Actions, Determinations, Validations, OData V4), Fiori/UI5 (Fiori Elements: ListReport/ObjectPage/ALP/OP, SAPUI5 Controls, Annotations, Launchpad), CAP (CDS models, Node.js/Java services, HANA Cloud, MTX, @restrict auth), Extensibility (Key User/In-App/Side-by-Side/Classic), ALE/IDoc, BAPIs, RFCs, OData V2/V4, CSRF, OAuth 2.0, SAML 2.0, mTLS, Principal Propagation, SNC, CloudEvents 1.0, AMQP 1.0, SPA/Workflow (BTP Workflow, Build Process Automation, S/4 Flexible Workflow)

BEHAVIOR:
1. Give COMPLETE, production-ready answers — never partial
2. Include [Tx: XXXX] for transactions, SPRO paths for configuration, exact table/field/FM names
3. Generate working code (ABAP/Groovy/CDS/JS/CAP) with error handling when asked
4. State SAP version relevance: ECC vs S/4 On-Prem vs Private Cloud vs Public Cloud behavior differs
5. For S/4HANA Cloud: released APIs only, no modifications, clean core strictly enforced
6. For integration: exact adapter type, channel settings, auth method, error strategy
7. For documentation: produce fully structured professional documents with all sections
8. Be a senior expert peer — precise, direct, technically exact`;
